# Generated by Django 5.2.9 on 2025-12-15 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliorequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='portfoliotemplate',
            options={},
        ),
        migrations.RemoveField(
            model_name='portfoliotemplate',
            name='template_file_path',
        ),
        migrations.RemoveField(
            model_name='portfoliotemplate',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='portfoliorequest',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_generated_portfolio', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
