# Generated by Django 5.2.9 on 2025-12-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_portfoliorequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gemini_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
