# Generated by Django 5.2.9 on 2025-12-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_premiumwaitlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vercel_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vercel_team_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
