"""
Django settings for portfolio_builder project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load configuration from config.properties file
def load_properties(filepath):
    """Load properties from a .properties file"""
    props = {}
    try:
        with open(filepath, 'r') as f:
            for line in f:
                line = line.strip()
                # Skip empty lines and comments
                if line and not line.startswith('#'):
                    # Split on first = sign
                    if '=' in line:
                        key, value = line.split('=', 1)
                        props[key.strip()] = value.strip()
    except FileNotFoundError:
        print(f"Warning: {filepath} not found. Using default configuration.")
    return props

# Load properties from config.properties
config_path = BASE_DIR / 'config.properties'
config = load_properties(config_path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^=$1*it1+0kg4r#1_e4v#&8m-g%k!ocjcc87w0*1%i2rq-ch=n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['.vercel.app', '127.0.0.1', 'localhost', 'portfoliomaker.mritunjay.live', '.mritunjay.live']

# Allow Google Sign-In popups
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.VisitorTrackingMiddleware',
]

ROOT_URLCONF = 'portfolio_builder.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Firebase Configuration
import firebase_admin

# Path to service account key file
FIREBASE_CREDENTIALS_PATH = config.get('FIREBASE_CREDENTIALS_PATH', 'firebase-adminsdk.json')

# Initialize Firebase Admin SDK
try:
    import firebase_admin
    from firebase_admin import credentials

    cred_path = FIREBASE_CREDENTIALS_PATH
    
    if os.path.exists(cred_path):
        cred = credentials.Certificate(cred_path)
    else:
        # Fallback for Vercel: Read from Environment Variable
        import json
        json_config = os.environ.get('FIREBASE_CREDENTIALS_JSON')
        if json_config:
            cred_dict = json.loads(json_config)
            cred = credentials.Certificate(cred_dict)
        else:
            cred = None
            print("Warning: Firebase credentials not found (File or Env Var)")

    if cred and not firebase_admin._apps:
        firebase_admin.initialize_app(cred)
except ImportError:
    print("Firebase Admin SDK not installed.")
except Exception as e:
    print(f"Error initializing Firebase: {e}")

# Firebase Client Config (for frontend)
# Firebase Client Config (for frontend)
FIREBASE_API_KEY = config.get('FIREBASE_API_KEY', os.environ.get('FIREBASE_API_KEY', ''))
FIREBASE_AUTH_DOMAIN = config.get('FIREBASE_AUTH_DOMAIN', os.environ.get('FIREBASE_AUTH_DOMAIN', ''))
FIREBASE_PROJECT_ID = config.get('FIREBASE_PROJECT_ID', os.environ.get('FIREBASE_PROJECT_ID', ''))
FIREBASE_STORAGE_BUCKET = config.get('FIREBASE_STORAGE_BUCKET', os.environ.get('FIREBASE_STORAGE_BUCKET', ''))
FIREBASE_MESSAGING_SENDER_ID = config.get('FIREBASE_MESSAGING_SENDER_ID', os.environ.get('FIREBASE_MESSAGING_SENDER_ID', ''))
FIREBASE_APP_ID = config.get('FIREBASE_APP_ID', os.environ.get('FIREBASE_APP_ID', ''))

WSGI_APPLICATION = 'portfolio_builder.wsgi.app'  # Changed for Vercel


import dj_database_url

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Update database configuration from $DATABASE_URL or $POSTGRES_URL (for Vercel Postgres)
# Update database configuration from config.properties or Environment Variables
# Update database configuration from config.properties or Environment Variables
db_url = config.get('DATABASE_URL') or \
         config.get('POSTGRES_URL') or \
         config.get('NILEDB_URL') or \
         config.get('NILEDB_POSTGRES_URL') or \
         os.environ.get('DATABASE_URL') or \
         os.environ.get('POSTGRES_URL') or \
         os.environ.get('POSTGRES_PRISMA_URL') or \
         os.environ.get('POSTGRES_URL_NON_POOLING') or \
         os.environ.get('NILEDB_URL') or \
         os.environ.get('NILEDB_POSTGRES_URL')

print(f"DEBUG: Config keys: {list(config.keys())}")
print(f"DEBUG: NILEDB_URL in config: '{config.get('NILEDB_URL')}'")
print(f"DEBUG: db_url initially: '{db_url}'")

if db_url:
    # Fix protocol for Django (postgres:// -> postgresql://)
    if db_url.startswith('postgres://'):
        db_url = db_url.replace('postgres://', 'postgresql://', 1)
    
    print(f"Using Database URL: {db_url[:15]}...") # Log start of URL for debugging
    
    db_from_env = dj_database_url.parse(db_url, conn_max_age=600)
    DATABASES['default'].update(db_from_env)
else:
    print("Using Local SQLite Database")

print(f"Active Database Engine: {DATABASES['default']['ENGINE']}")


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'core' / 'static',
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session configuration - Use Signed Cookies for Vercel (No DB required)
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
SESSION_COOKIE_AGE = 86400  # 24 hours

# Gemini API Configuration
GEMINI_API_KEY = config.get('GEMINI_API_KEY', os.environ.get('GEMINI_API_KEY', ''))

# Admin Access
# Parse comma-separated string into a list
admin_emails_str = config.get('ADMIN_EMAILS', os.environ.get('ADMIN_EMAILS', ''))
ADMIN_EMAILS = [email.strip() for email in admin_emails_str.split(',') if email.strip()]


